### ISSUE TITLE
最后实现的效果

### ISSUE THREAD

**Issue by Datou98** [292213017/vins_coloroctomap#1]
你好，我想问一下有最后的实现效果图吗？如果要自己给slam添加octomap，建议怎么开始弄比较好？

**Comment by Clouds1997** [comment]
效果图更新到readme了，你可以参考这个工程中后端部分

**Comment by Datou98** [comment]
我刚才看了一下，您是还加了yolov4检测？方便加个联系方式吗？有些问题想请教您



---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2022年10月23日(週日) 中午11:10
收件人： ***@***.***&gt;;
抄送： ***@***.******@***.***&gt;;
主旨： Re: [Clouds1997/vins_coloroctomap] 最后实现的效果 (Issue #1)




 
效果图更新到readme了，你可以参考这个工程中后端部分

**Comment by Clouds1997** [comment]
加yolo是为了去动态，不然人什么的会留下残影，这个工程已经很久啦，所以我可能已经不能提供什么参考意见啦

**Comment by Datou98** [comment]
好的，非常感谢



---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2022年10月23日(週日) 中午12:04
收件人： ***@***.***&gt;;
抄送： ***@***.******@***.***&gt;;
主旨： Re: [Clouds1997/vins_coloroctomap] 最后实现的效果 (Issue #1)




 
加yolo是为了去动态，不然人什么的会留下残影，这个工程已经很久啦，所以我可能已经不能提供什么参考意见啦
